name: Build

on:
  push:
  pull_request:
  release:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: [3.2, 3.3, 3.4, jruby]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Update RubyGems and Bundler
        run: |
          gem update --system
          gem update bundler

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Test
        run: bundle exec rake
